name: flutter_text_field_fab
description: A new Flutter package project.
version: 0.0.3
homepage: "https://www.haefelesoftware.com/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.haefelesoftware.fluttertextfieldfab
        pluginClass: TextFieldFloatingActionButton
      ios:
        pluginClass: TextFieldFloatingActionButton
      macos:
        pluginClass: TextFieldFloatingActionButton
      web:
        pluginClass: TextFieldFloatingActionButton
