name: flutter_text_field_fab
description: flutter_text_field_fab is a simple widget that allows you to turn a floating action button into a text field.
version: 0.0.4
homepage: "https://www.haefelesoftware.com/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
